### ISSUE TITLE
Unicode絵文字の読み上げ

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#15]
- close https://github.com/jaoafa/jao-Minecraft-Server/issues/180

`😀`  → `:grinning:` のような置き換えをしたうえでVoiceTextに投げる処理が必要。

`src/main/kotlin/com/jaoafa/vcspeaker/tools/Emoji.kt` でライブラリっぽいものはあるが、まだ利用されていない模様

**Comment by yuuahp** [comment]
絵文字名って英語でよかったっけ

**Comment by book000** [comment]
Yes
https://github.com/jaoafa/JDA-VCSpeaker/blob/0cccc184362345e8000f989e98525145ee4742ec/src/main/java/com/jaoafa/jdavcspeaker/Lib/EmojiWrapper.java#L22

**Comment by book000** [comment]
実装めんどくさかったら、com.vdurmont.emoji.EmojiManagerが使える

**Comment by yuuahp** [comment]
実はもうできた

**Comment by yuuahp** [comment]
再起動されたので閉じます
