### ISSUE TITLE
マージキューの有効化

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#154]
Update branchを押さないとマージされないのがなかなかすぎる。

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by book000** [comment]
@yuuahp これ、おてすきのときに試してもらえませんか？
workflowのtriggerに追加するとかもあるっぽいけど

**Comment by yuuahp** [comment]
✅

**Comment by yuuahp** [comment]
(試してはないけど)
