### ISSUE TITLE
絵文字エイリアスが正しく置き換えられない

### ISSUE THREAD

**Issue by jaotan** [jaoafa/VCSpeaker.kt#160]
# 不具合報告

NULL

## 不具合と思われるメッセージ (または報告)

2024-06-23 11:49:28.678 に送信された `TomachiTestBot` による `#vc` でのメッセージ

メッセージURL: https://discord.com/channels/1138605145660326040/1149605620027232276/1254267053368410133

## 不具合報告者

`za96` (`206692134991036416`)

**Comment by book000** [comment]
@yuuahp なんか、AliasReplacer より前に GuildEmojiReplacer が走ることによって絵文字のエイリアスが動作しないみたいです
さてどうしましょう
