### ISSUE TITLE
Docker support & Continuous Delivery

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#2]
- `ghcr.io/jaoafa/vcspeaker.kt` あたりでDockerパッケージが公開されることを期待
- リリースを切ったのと同時にDockerパッケージを作るのか、mainにマージされた瞬間に自動でバージョンを切ってDockerパッケージを作るのか、方針がわからない
- 参考までに、いつも使ってるリリーステンプレート: https://github.com/book000/templates/blob/master/.github/workflows/reusable-docker.yml

Dockerfileくらいなら書くけど、リリースCDはゆうあ氏に作って欲しい。

**Comment by book000** [comment]
gradlewが動くようになった筈なので、gradlewを使った形でのビルドDockerfileをプルリクする。

**Comment by yuuahp** [comment]
あもう作ってる？

**Comment by book000** [comment]
ラズパイで動かすにあたって、どっちにしてもDockerfileは書いてます
CDそのものは使ってません

**Comment by book000** [comment]
Closed by https://github.com/jaoafa/VCSpeaker.kt/commit/93820916594dc994c8d2e6f02a990b0dbc7921d2 & #18
