### ISSUE TITLE
VisionAPIによる画像の文字起こし機能の実装

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#23]
https://github.com/jaoafa/JDA-VCSpeaker/blob/main/src/main/java/com/jaoafa/jdavcspeaker/Lib/VisionAPI.java

Label detectionはせず、Text detectionのみ行う。

1. ファイルの拡張子によって、画像かそうでないかを判別し「画像処理」と「ファイル処理」に分ける
2. 無料範囲内を超えるリクエストになってしまう場合はやめる（ファイル処理へ移行）
3. 画像ファイルをテンポラリディレクトリにダウンロードする
4. MimeTypeを取得し、適切なMimeTypeか確認する（ダメならファイル処理に移行）
5. 画像の中身をmd5などでハッシュ化し、キャッシュが存在するかを確認する
6. base64で画像ファイルの中身をエンコードする
7. VisionAPIのエンドポイントへリクエストを投げる。リクエスト回数をカウントする
8. レスポンスを処理し、文字列・文字の位置を取得し保存する。
9. 画像を編集し、文字列がどの位置にあるかを示す画像を作成する。
10. 適宜読み上げたり投稿する。

結果はキャッシュし、ハッシュ値が同じであればキャッシュレスポンスを利用。

**Comment by book000** [comment]
疑問: Okhttp以外に、なんかマシなHTTPクライアントライブラリはあるのかしら。

**Comment by yuuahp** [comment]
たぶん VoiceTextAPI と同じで Ktor 使うと思う

**Comment by yuuahp** [comment]
もしかして VisionAPI ってクレジットカード必須ですか？

**Comment by book000** [comment]
そうかも。

**Comment by yuuahp** [comment]
ダメです。

**Comment by book000** [comment]
うーん、ちょっと内々で話させてください
