### ISSUE TITLE
変更可能なフォルダパス

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#3]
https://github.com/jaoafa/VCSpeaker.kt/blob/d1fb3df68bb12087e7ace32b7ef673af60827d18/src/main/kotlin/com/jaoafa/vcspeaker/VCSpeaker.kt#L112-L113

storesディレクトリ、cachesディレクトリはカレントディレクトリに作成されてしまうようです。
Docker環境下で動かす場合、これらのディレクトリはボリューム対象ディレクトリとしたいと考えます。

`config.yml` のように、引数または環境変数でこれらのパスを変更できると嬉しく思います。
（`config.yml` についても、本当は環境変数**でも**いじれたらいいなと思いますが…まあ。）

**Comment by yuuahp** [comment]
やりました。
とりあえず discord に書きましたがドキュメントも後で書きます。
