### ISSUE TITLE
フォーク先のプルリクエストの場合にCIが落ちる

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#32]
`thollander/actions-comment-pull-request@v2` を使っていますが、これは pull_requestトリガーの場合フォークだと `Error: Resource not accessible by integration` が発生します。

pull_request_targetだと正常に動作しますが、悪意を持ったユーザがsecretを抜き取るプルリクエストを発行した場合に抜き取られる恐れがあります。

ビルド成功・失敗メッセージいらんかな？とも思っていますが、いかがでしょうか。もし必要なら、ラベルトリガーによるCI動作（jaoweb4あたりを参照）が必要です。

**Comment by yuuahp** [comment]
消しました✅
