### ISSUE TITLE
MkDocs documentation for users & devs

### ISSUE THREAD

**Issue by yuuahp** [jaoafa/VCSpeaker.kt#33]
MKDocs を使って wiki を作ります。
- /docs/for-developers /docs/for-users みたいな
- Material for MKDocs 使いたい

**Comment by book000** [comment]
mkdocsって例には上げましたが、あくまで私の知見があるツールというだけで、選択の余地はあると思います
色々吟味してもらえれば…。

**Comment by book000** [comment]
あと、wikiなのかドキュメントなのか、一応統一しておきましょうか…

wikiは言葉の定義上はウェブブラウザから直接編集できるシステムのことを指します
ドキュメントは資料とか記録なので言葉の範囲は広いです

**Comment by yuuahp** [comment]
> mkdocsって例には上げましたが、あくまで私の知見があるツールというだけで、選択の余地はあると思います 色々吟味してもらえれば…。

一応色々探してみた結果です

**Comment by yuuahp** [comment]
> あと、wikiなのかドキュメントなのか、一応統一しておきましょうか…（サイトタイトルにもなると思うので）
> 
> wikiは言葉の定義上はウェブブラウザから直接編集できるシステムのことを指します ドキュメントは資料とか記録なので言葉の範囲は広いです

置き場所も docs になりそうだし、そういう意味なら document ってことにしておきます

**Comment by book000** [comment]
とりあえずユーザー向けには作ろうかと思いますが、コマンド一覧以外に何か欲しいページありますか？

- for-users
  - commands
    - alias.md
    - clear.md
    - ignore.md
    - join.md
    - leave.md
    - parse.md
    - reset-title.md
    - save-title.md
    - speak.md
    - title.md
    - vcspeaker.md
    - voice.md

**Comment by yuuahp** [comment]
features の全体的な説明とか？

**Comment by book000** [comment]
featuresというと、alias, title, ignore？
それらってコマンドページで説明すると微妙ですかね？

**Comment by yuuahp** [comment]
例えば features ページで Alias が何をしてくれるのかを説明して、commands ページで Alias をどう扱うのかを説明するみたいなのをイメージしてた

**Comment by book000** [comment]
naruhodo
