### ISSUE TITLE
画像URLだけの文字列が読み上げられない？

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#38]
誰も報告してないんですけど、まあ気がついたので…

![IMG_3027](https://github.com/jaoafa/VCSpeaker.kt/assets/8929706/9b7672b4-740f-459f-bcde-a1f7b4edba92)

**Comment by yuuahp** [comment]
https://github.com/jaoafa/VCSpeaker.kt/blob/df02e3dc0c131614fe4bcd05b3f70c4b741771dc/src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt#L195
titleタグがないからかな？
直します

**Comment by book000** [comment]
titleタグがない場合、読み上げ文字列が置き換えられずに次の置き換え処理いくからこれで良いと思ったんだよね
デバッグきちんとしないと駄目そう

**Comment by yuuahp** [comment]
てっきり null になって読み上げスキップされてるのかと思ったらなんか MalformedInputException してる

**Comment by yuuahp** [comment]
https://youtrack.jetbrains.com/issue/KTOR-5247/Ktor-throws-MalformedInputException-unexpectedly
文字コードが UTF-8 じゃないのが原因っぽいので、これに書いてある回避策(?)使います

**Comment by yuuahp** [comment]
直しました。
テスト中に url より拡張子が優先されてることに気が付いたのでこれもあとで直します。
(例えば、`https://github.com/jaoafa/VCSpeaker.kt/issues/38` が「kt/issues/38ファイルへのリンク」になる。`.kt/issues/38` という拡張子って認識されてそう。)

**Comment by book000** [comment]
PRにしてレビュアー入れてくれたらこっちでも変更確認できたのに……ってのはまあいいか。

 バイト文字列で取ってきてStringにしてしまう、なるほどね。

拡張子を読み上げるのは本当に最後（タイトル取得とかより後）、 replaceUメソッドでやっています
なので、優先度はおかしくないはずなんですが…GitHubへのアクセス時、CloudflareとかにHTMLの取得ブロックされたんですかね？
極論、5文字以上の拡張子は無理に読み上げなくても良いかもしれません。

**Comment by yuuahp** [comment]
GitHub は 406 が出てたので title は取得されてなさそう
あと PR にすればよかったのはそれはそうかも...

**Comment by book000** [comment]
406！？Not Acceptable！？
Accept: text/htmlとか入れなきゃダメなのか…？？？

個人的には、ブランチプロテクションつけてゆうあ氏含めてフォークからPR投げてやる形にしても良いんじゃないかなって思ってたりします。もしゆうあ氏が私のレビュー受けんのめんどいって言うならjaotan review入れても良いし。

**Comment by yuuahp** [comment]
ブランチプロテクションつけました。
まあ別にすぐにマージしたいこととかあんまりないし、これからレビューリクエストするようにします👍
