### ISSUE TITLE
装飾文字を処理する

### ISSUE THREAD

**Issue by yuuahp** [jaoafa/VCSpeaker.kt#42]
Markdown の特殊文字をちゃんと処理する (場合によっては読み方も変える)

**Comment by book000** [comment]
装飾文字パターン

- h1, h2, h3
- 太字（`**text**`）
- 斜体（`_text_`）
- 下線（`__text__`）
- 取消（`~~text~~`）
- リスト（`- text`）
- 番号付きリスト（`1. text`）
- スポイラー（`||text||`）
- コードブロック
- インラインコードブロック
- 引用（`> text`）

**Comment by book000** [comment]
装飾文字に対する対応

- h1, h2, h3: 指定されたハッシュの個数に応じて読み上げスピードを変更
- 取消: `パー` に置き換え
- スポイラー: `ピー` に置き換え。URLも考慮する
- コードブロック: 読み上げない

**Comment by yuuahp** [comment]
わかったことメモ:
- 重ね掛けは一方がもう一方を完全に含んでいなければいけない
- 交差している場合は先に記号が来るほうが優先 (`**Mark__down** Text__` の場合は太字だけ掛かって下線は無効化される)
- Heading みたいに一行にかかる装飾も重ねられる (`> # Heading Quote`)
  - 実は行頭でなくてもいける (`__# Heading 1__` みたいなことができる)
  - 文字が成立してしまった時点でそれ以降の一行装飾は無視される
    - `a > # Markdown` は当然なにも掛からない
    - `> a # Quote` は引用だけ掛かる
    - `> __ # Underline Quote Heading__` は全部掛かる (`__`は装飾に使われるため)

**Comment by yuuahp** [comment]
![image](https://github.com/jaoafa/VCSpeaker.kt/assets/53546237/e3185ac5-d94c-4ae2-babe-28428fc1ad92)
進捗
もしかしたら今ある Replacer もこれに統合できるかも

あとちょっと試してみたんだけど、文章内で装飾ごとに音声を変えて繋げるのは厳しそう (イントネーションが変わるっぽい)

**Comment by book000** [comment]
良さそう

VoiceTextAPIの依存をやめるというのも一つの手ですよ
フリーで上限が無いもしくは緩く、またはローカルであまり負荷なく(CPUのみで)生成できることが前提条件ですが…
Dockerで動いているので、ローカルでのText to Speechは有力な案かもしれない

**Comment by book000** [comment]
- h1, h2, h3: 指定されたハッシュの個数に応じて読み上げスピードを変更

これ未対応なのでreopenしました

あと、取り消し線が `パー` になってない気がします
https://discord.com/channels/1138605145660326040/1149605620027232276/1218569288093536326

**Comment by yuuahp** [comment]
最新のコンテナー pull して動かしてみましたが普通にパーになります

**Comment by book000** [comment]
`docker compose down --rmi all --volumes --remove-orphans` でイメージとか吹っ飛ばして立ち上げなおしたけど、ダメそう…。
そっちでZakuroHatつないでためしてみてほしい

**Comment by yuuahp** [comment]
えー、Alias でした。

**Comment by yuuahp** [comment]
普通に動きました

**Comment by book000** [comment]
動いたってことなのでクローズします
