### ISSUE TITLE
最後の一人がAFKになった時、タイトルがリセットされない

### ISSUE THREAD

**Issue by jaotan** [jaoafa/VCSpeaker.kt#47]
# 不具合報告

手動でチャンネルを移動した時にはリセットされていると思うので、自動でAFKに移動された時だけリセットされていないと思います。

## 不具合と思われるメッセージ (または報告)

2023-11-02 03:54:26.701 に送信された `TomachiTestBot` による `#vc` でのメッセージ

メッセージURL: https://discord.com/channels/1138605145660326040/1149605620027232276/1169348746862145586

## 不具合報告者

`sjcl` (`218282853752897536`)

**Comment by book000** [comment]
なんか、このへんがおかしい気がします。

https://github.com/jaoafa/VCSpeaker.kt/blob/08fa33a114c9c3bc904d9b357c808d843131d94d/src/main/kotlin/com/jaoafa/vcspeaker/events/TitleEvent.kt#L22

ちょっとデバッグしましたが、AFKに移動するとこうなります

```
TitleEvent: check: false
TitleEvent: check: true
TitleEvent: check: 0
```
