### ISSUE TITLE
画像を添付するとテキストが読み上げられません

### ISSUE THREAD

**Issue by jaotan** [jaoafa/VCSpeaker.kt#48]
# 不具合報告

画像を添付するとテキストが読み上げられないから

## 不具合と思われるメッセージ (または報告)

2023-11-05 01:01:45.471 に送信された `kohonayoshi` による `#vc` でのメッセージ

メッセージURL: https://discord.com/channels/1138605145660326040/1149605620027232276/1170392452310503494

## 不具合報告者

`kohonayoshi` (`315726390844719114`)

**Comment by book000** [comment]
このへんが悪さしてるのかしら？
https://github.com/jaoafa/VCSpeaker.kt/blob/08fa33a114c9c3bc904d9b357c808d843131d94d/src/main/kotlin/com/jaoafa/vcspeaker/voicetext/MessageProcessor.kt#L16
