### ISSUE TITLE
CodeQL CIのエラーに対応する

### ISSUE THREAD

**Issue by book000** [jaoafa/VCSpeaker.kt#77]
やめる or なんとかする

**Comment by yuuahp** [comment]
Actions のメモリー量ってどれくらいだっけ？
Java が勝手に制限してて全体としては全然使ってないって可能性はあるかも。

**Comment by book000** [comment]
Linux: 16 GB

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

まあ、16GBまるまる食ってたら流石に笑ってしまうのでJavaかそれ以外で何かしらの制約がかかってそうですね

**Comment by book000** [comment]
> Not enough memory to run compilation. Try to increase it via 'gradle.properties':
> kotlin.daemon.jvmargs=-Xmx<size>

https://github.com/orgs/community/discussions/25430
https://zenn.dev/eichisanden/scraps/b765f7155f5ad0

**Comment by book000** [comment]
jvmargsで回避…うーん…

**Comment by yuuahp** [comment]
メモリのない環境でも占有されるかもしれないからアレってこと？

**Comment by book000** [comment]
まあはい。gradle.propertiesに指定するということはCodeQL以外の環境でもRAM割当されるってことですよねえ
やるならCodeQL内だけでやりたい

**Comment by book000** [comment]
てか、CodeQLこれGitHub Actionsの制約条件と合うのか？VCSpeaker.ktのCodeQLってWorkflow書いてないですよね

**Comment by book000** [comment]
とりあえず、全部が全部❌つくのよくないのでなんとかしたいですね
一旦無効化するなり

**Comment by yuuahp** [comment]
めちゃくちゃ遅れましたが直しました
Advanced Configuration に切り替えて、2G 割り当てました。
とりあえずクローズします。
